services:
    app:
        build: .
        ports:
            - "8000:8000"

        environment:
            - APP_NAME='Task Manager Laravel App'
            - APP_ENV=production
            - APP_KEY=base64:4T+pD+wO/XQ6oE/Fh/rE/v/Q/jY6QYjE=
            - APP_DEBUG=false
            - APP_URL=https://task.leandrogrc.dev
            - APP_LOCALE=pt_BR
            - APP_FALLBACK_LOCALE=pt_BR
            - APP_FAKER_LOCALE=pt_BR
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - shared_network

networks:
    shared_network:
        external: true