services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
        user: "1000:www-data"
        environment:
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
